Dataset
CosmoStat/autometacal pull request #10
Opened 2021-04-13 12:33 UTC by andrevitorelli

2021-04-13 12:51 UTC, EiffL commented
I think it's looking good :-) but could you update your branch to `main`? so that I can see if it works when the package is installed?

2021-04-13 15:05 UTC, EiffL requested changes
Looking good :-) Thanks Andre! 
I found an issue when trying to import the GalGen object, but that should be easily fixable.

2021-04-13 15:05 UTC, EiffL commented on autometacal/python/datasets/gal_gen.py
> +from galaxies import generate_galaxy
This doesn't seem to work, maybe use this instead for now:
```python
from .galaxies import generate_galaxy
```

2021-04-27 12:51 UTC, b-remy commented
I added a `BuilderConfig` class to the `gal_gen.py` dataset file that enables to creates variants.

We can specify for instance stamp size, pixel size or the flux, parameters that are used to create galaxy images with `datasets/galaxies.py`.

Specifying the name and parameters of your variant such as:
```python
GalGenConfig(name='variant1', stamp_size=50, pixel_scale=.2, flux=1.)
```
you can call it with:
```python
tfds.load('GalGen/variant1')
```

2021-04-27 13:21 UTC, EiffL commented
\o/ this is great :-D Thanks @b-remy

2021-04-27 13:22 UTC, EiffL approved these changes
LGTM!

2021-04-27 13:23 UTC, EiffL commented
Many thanks @andrevitorelli  and @b-remy ! Let's use this dataset as our baseline for now, we can add additional features as they are needed for the next steps of the project, for instance PSF and/or Fourier image of the galaxies. 

I'm going to go ahead and merge this :-)

2021-04-27 13:23 UTC, closed without merging